version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: task3-timescaledb
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fitbit_data
    ports:
      - "5432:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - wearipedia-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  ingestion:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task3-modified-ingestion
    environment:
      - DB_HOST=timescaledb
      - DB_PORT=5432
      - DB_NAME=fitbit_data
      - DB_USER=postgres
      - DB_PASSWORD=password
      # Set TEST_MODE to "true" to run in test mode
      - TEST_MODE=${TEST_MODE:-false}
      # Set CATCH_UP_MODE to "true" to run in catch-up mode
      - CATCH_UP_MODE=${CATCH_UP_MODE:-false}
      # Set RESET_MODE to "true" to run in reset mode
      - RESET_MODE=${RESET_MODE:-false}
      - DATA_DIR=/app/Data/Modified\ Data
    volumes:
      - .:/app
      - ../Data:/app/Data
    depends_on:
      timescaledb:
        condition: service_healthy
    networks:
      - wearipedia-net

volumes:
  timescaledb_data:

networks:
  wearipedia-net:
    driver: bridge