services:
  timescaledb:
    image: timescale/timescaledb:latest-pg17
    environment:
      POSTGRES_DB: fitbit_data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - timescale_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fitbit_data"]
      interval: 10s
      timeout: 5s
      retries: 5

  ingestion:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      timescaledb:
        condition: service_healthy
    environment:
      - DB_HOST=timescaledb
      - DB_PORT=5432
      - DB_NAME=fitbit_data
      - DB_USER=postgres
      - DB_PASSWORD=password
      - TEST_MODE=${TEST_MODE:-false}
      - TEST_INTERVAL=${TEST_INTERVAL:-300}
    volumes:
      - ../Data:/app/Data
      - ingestion_state:/app/state
      - ./logs:/var/log

volumes:
  timescale_data:
  ingestion_state: