-- Create users table
CREATE TABLE IF NOT EXISTS USERS (
    USER_ID INT PRIMARY KEY,
    NAME TEXT,
    EMAIL TEXT,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW()
);

-- Create devices table
CREATE TABLE IF NOT EXISTS DEVICES (
    DEVICE_ID TEXT PRIMARY KEY,
    USER_ID INT REFERENCES USERS(USER_ID),
    DEVICE_TYPE TEXT NOT NULL,
    MODEL TEXT,
    REGISTERED_AT TIMESTAMPTZ DEFAULT NOW()
);

-- Create heart rate table
CREATE TABLE IF NOT EXISTS HEART_RATE (
    ID BIGSERIAL,
    USER_ID INT REFERENCES USERS(USER_ID),
    DEVICE_ID TEXT REFERENCES DEVICES(DEVICE_ID),
    TIMESTAMP TIMESTAMPTZ NOT NULL,
    VALUE INT NOT NULL,
    RESTING_HEART_RATE INT,
    ZONES JSONB,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (ID, TIMESTAMP)
);

-- Create SpO2 table
CREATE TABLE IF NOT EXISTS SPO2 (
    ID BIGSERIAL,
    USER_ID INT REFERENCES USERS(USER_ID),
    DEVICE_ID TEXT REFERENCES DEVICES(DEVICE_ID),
    TIMESTAMP TIMESTAMPTZ NOT NULL,
    VALUE FLOAT NOT NULL,
    MINUTE_DATA JSONB,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (ID, TIMESTAMP)
);

-- Create HRV table
CREATE TABLE IF NOT EXISTS HRV (
    ID BIGSERIAL,
    USER_ID INT REFERENCES USERS(USER_ID),
    DEVICE_ID TEXT REFERENCES DEVICES(DEVICE_ID),
    TIMESTAMP TIMESTAMPTZ NOT NULL,
    RMSSD FLOAT,
    COVERAGE FLOAT,
    HF FLOAT,
    LF FLOAT,
    MINUTE_DATA JSONB,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (ID, TIMESTAMP)
);

-- Create breathing rate table
CREATE TABLE IF NOT EXISTS BREATHING_RATE (
    ID BIGSERIAL,
    USER_ID INT REFERENCES USERS(USER_ID),
    DEVICE_ID TEXT REFERENCES DEVICES(DEVICE_ID),
    TIMESTAMP TIMESTAMPTZ NOT NULL,
    DEEP_SLEEP_RATE FLOAT,
    REM_SLEEP_RATE FLOAT,
    LIGHT_SLEEP_RATE FLOAT,
    FULL_SLEEP_RATE FLOAT,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (ID, TIMESTAMP)
);

-- Create active zone minutes table
CREATE TABLE IF NOT EXISTS ACTIVE_ZONE_MINUTES (
    ID BIGSERIAL,
    USER_ID INT REFERENCES USERS(USER_ID),
    DEVICE_ID TEXT REFERENCES DEVICES(DEVICE_ID),
    TIMESTAMP TIMESTAMPTZ NOT NULL,
    FAT_BURN_MINUTES INT,
    CARDIO_MINUTES INT,
    PEAK_MINUTES INT,
    ACTIVE_ZONE_MINUTES INT,
    MINUTE_DATA JSONB,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (ID, TIMESTAMP)
);

-- Create activity table
CREATE TABLE IF NOT EXISTS ACTIVITY (
    ID BIGSERIAL,
    USER_ID INT REFERENCES USERS(USER_ID),
    DEVICE_ID TEXT REFERENCES DEVICES(DEVICE_ID),
    TIMESTAMP TIMESTAMPTZ NOT NULL,
    VALUE INT NOT NULL,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (ID, TIMESTAMP)
);

-- Create last_processed_dates table for tracking timestamps
CREATE TABLE IF NOT EXISTS LAST_PROCESSED_DATES (
    METRIC_TYPE TEXT PRIMARY KEY,
    USER_ID INT,
    LAST_PROCESSED_DATE TIMESTAMPTZ NOT NULL,
    UPDATED_AT TIMESTAMPTZ DEFAULT NOW()
);

-- Convert tables to TimescaleDB hypertables
SELECT
    CREATE_HYPERTABLE('heart_rate', 'timestamp', IF_NOT_EXISTS => TRUE);

SELECT
    CREATE_HYPERTABLE('spo2', 'timestamp', IF_NOT_EXISTS => TRUE);

SELECT
    CREATE_HYPERTABLE('hrv', 'timestamp', IF_NOT_EXISTS => TRUE);

SELECT
    CREATE_HYPERTABLE('breathing_rate', 'timestamp', IF_NOT_EXISTS => TRUE);

SELECT
    CREATE_HYPERTABLE('active_zone_minutes', 'timestamp', IF_NOT_EXISTS => TRUE);

SELECT
    CREATE_HYPERTABLE('activity', 'timestamp', IF_NOT_EXISTS => TRUE);

-- Create indexes for efficient querying
-- Heart Rate indexes
CREATE INDEX IF NOT EXISTS IDX_HEART_RATE_USER_ID ON HEART_RATE (USER_ID);

CREATE INDEX IF NOT EXISTS IDX_HEART_RATE_DEVICE_ID ON HEART_RATE (DEVICE_ID);

CREATE INDEX IF NOT EXISTS IDX_HEART_RATE_TIMESTAMP ON HEART_RATE (TIMESTAMP);

CREATE INDEX IF NOT EXISTS IDX_HEART_RATE_USER_TIME ON HEART_RATE (USER_ID, TIMESTAMP);

-- SpO2 indexes
CREATE INDEX IF NOT EXISTS IDX_SPO2_USER_ID ON SPO2 (USER_ID);

CREATE INDEX IF NOT EXISTS IDX_SPO2_DEVICE_ID ON SPO2 (DEVICE_ID);

CREATE INDEX IF NOT EXISTS IDX_SPO2_TIMESTAMP ON SPO2 (TIMESTAMP);

CREATE INDEX IF NOT EXISTS IDX_SPO2_USER_TIME ON SPO2 (USER_ID, TIMESTAMP);

-- HRV indexes
CREATE INDEX IF NOT EXISTS IDX_HRV_USER_ID ON HRV (USER_ID);

CREATE INDEX IF NOT EXISTS IDX_HRV_DEVICE_ID ON HRV (DEVICE_ID);

CREATE INDEX IF NOT EXISTS IDX_HRV_TIMESTAMP ON HRV (TIMESTAMP);

CREATE INDEX IF NOT EXISTS IDX_HRV_USER_TIME ON HRV (USER_ID, TIMESTAMP);

-- Breathing Rate indexes
CREATE INDEX IF NOT EXISTS IDX_BREATHING_RATE_USER_ID ON BREATHING_RATE (USER_ID);

CREATE INDEX IF NOT EXISTS IDX_BREATHING_RATE_DEVICE_ID ON BREATHING_RATE (DEVICE_ID);

CREATE INDEX IF NOT EXISTS IDX_BREATHING_RATE_TIMESTAMP ON BREATHING_RATE (TIMESTAMP);

CREATE INDEX IF NOT EXISTS IDX_BREATHING_RATE_USER_TIME ON BREATHING_RATE (USER_ID, TIMESTAMP);

-- Active Zone Minutes indexes
CREATE INDEX IF NOT EXISTS IDX_ACTIVE_ZONE_MINUTES_USER_ID ON ACTIVE_ZONE_MINUTES (USER_ID);

CREATE INDEX IF NOT EXISTS IDX_ACTIVE_ZONE_MINUTES_DEVICE_ID ON ACTIVE_ZONE_MINUTES (DEVICE_ID);

CREATE INDEX IF NOT EXISTS IDX_ACTIVE_ZONE_MINUTES_TIMESTAMP ON ACTIVE_ZONE_MINUTES (TIMESTAMP);

CREATE INDEX IF NOT EXISTS IDX_ACTIVE_ZONE_MINUTES_USER_TIME ON ACTIVE_ZONE_MINUTES (USER_ID, TIMESTAMP);

-- Activity indexes
CREATE INDEX IF NOT EXISTS IDX_ACTIVITY_USER_ID ON ACTIVITY (USER_ID);

CREATE INDEX IF NOT EXISTS IDX_ACTIVITY_DEVICE_ID ON ACTIVITY (DEVICE_ID);

CREATE INDEX IF NOT EXISTS IDX_ACTIVITY_TIMESTAMP ON ACTIVITY (TIMESTAMP);

CREATE INDEX IF NOT EXISTS IDX_ACTIVITY_USER_TIME ON ACTIVITY (USER_ID, TIMESTAMP);

-- Last processed dates indexes
CREATE INDEX IF NOT EXISTS IDX_LAST_PROCESSED_DATES_METRIC_USER ON LAST_PROCESSED_DATES (METRIC_TYPE, USER_ID);