-- Create users table
CREATE TABLE IF NOT EXISTS USERS (
    USER_ID INT PRIMARY KEY,
    NAME TEXT,
    EMAIL TEXT,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW()
);

-- Create devices table
CREATE TABLE IF NOT EXISTS DEVICES (
    DEVICE_ID TEXT PRIMARY KEY,
    USER_ID INT REFERENCES USERS(USER_ID),
    DEVICE_TYPE TEXT NOT NULL,
    MODEL TEXT,
    REGISTERED_AT TIMESTAMPTZ DEFAULT NOW()
);

-- Create raw_data hypertable for all metrics
CREATE TABLE IF NOT EXISTS RAW_DATA (
    ID SERIAL PRIMARY KEY,
    METRIC_TYPE TEXT NOT NULL,
    USER_ID INT REFERENCES USERS(USER_ID),
    DEVICE_ID TEXT REFERENCES DEVICES(DEVICE_ID),
    TIMESTAMP TIMESTAMPTZ NOT NULL,
    VALUE JSONB NOT NULL
);

-- Convert to TimescaleDB hypertable
SELECT
    CREATE_HYPERTABLE('raw_data', 'timestamp', IF_NOT_EXISTS => TRUE);

-- Create index on metric_type
CREATE INDEX IF NOT EXISTS IDX_RAW_DATA_METRIC_TYPE ON RAW_DATA (METRIC_TYPE);

-- Create index on user_id
CREATE INDEX IF NOT EXISTS IDX_RAW_DATA_USER_ID ON RAW_DATA (USER_ID);

-- Create compound index for common query patterns
CREATE INDEX IF NOT EXISTS IDX_RAW_DATA_COMMON_QUERY
ON RAW_DATA (USER_ID, METRIC_TYPE, TIMESTAMP DESC);