-- Enable TimescaleDB extension
CREATE EXTENSION IF NOT EXISTS TIMESCALEDB CASCADE;

-- Create users table
CREATE TABLE IF NOT EXISTS USERS (
    USER_ID INT PRIMARY KEY,
    NAME TEXT,
    EMAIL TEXT,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW()
);

-- Create devices table
CREATE TABLE IF NOT EXISTS DEVICES (
    DEVICE_ID TEXT PRIMARY KEY,
    USER_ID INT REFERENCES USERS(USER_ID),
    DEVICE_TYPE TEXT NOT NULL,
    MODEL TEXT,
    REGISTERED_AT TIMESTAMPTZ DEFAULT NOW()
);

-- Create heart rate table
CREATE TABLE IF NOT EXISTS HEART_RATE (
    ID BIGSERIAL,
    USER_ID INT REFERENCES USERS(USER_ID),
    DEVICE_ID TEXT REFERENCES DEVICES(DEVICE_ID),
    TIMESTAMP TIMESTAMPTZ NOT NULL,
    VALUE INT,
    RESTING_HEART_RATE INT,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (ID, TIMESTAMP)
);

-- Heart rate zones table - fix primary key
CREATE TABLE IF NOT EXISTS HEART_RATE_ZONES (
    ID BIGSERIAL,
    USER_ID INT REFERENCES USERS(USER_ID),
    DEVICE_ID TEXT REFERENCES DEVICES(DEVICE_ID),
    TIMESTAMP TIMESTAMPTZ NOT NULL,
    ZONE_NAME TEXT,
    MIN_HR INT,
    MAX_HR INT,
    MINUTES INT,
    CALORIES_OUT FLOAT,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (ID, TIMESTAMP)
);

-- SpO2 table - fix primary key
CREATE TABLE IF NOT EXISTS SPO2 (
    ID BIGSERIAL,
    USER_ID INT REFERENCES USERS(USER_ID),
    DEVICE_ID TEXT REFERENCES DEVICES(DEVICE_ID),
    TIMESTAMP TIMESTAMPTZ NOT NULL,
    VALUE FLOAT,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (ID, TIMESTAMP)
);

-- HRV table - fix primary key
CREATE TABLE IF NOT EXISTS HRV (
    ID BIGSERIAL,
    USER_ID INT REFERENCES USERS(USER_ID),
    DEVICE_ID TEXT REFERENCES DEVICES(DEVICE_ID),
    TIMESTAMP TIMESTAMPTZ NOT NULL,
    RMSSD FLOAT,
    COVERAGE FLOAT,
    HF FLOAT,
    LF FLOAT,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (ID, TIMESTAMP)
);

-- Breathing rate table - fix primary key
CREATE TABLE IF NOT EXISTS BREATHING_RATE (
    ID BIGSERIAL,
    USER_ID INT REFERENCES USERS(USER_ID),
    DEVICE_ID TEXT REFERENCES DEVICES(DEVICE_ID),
    TIMESTAMP TIMESTAMPTZ NOT NULL,
    DEEP_SLEEP_RATE FLOAT,
    REM_SLEEP_RATE FLOAT,
    LIGHT_SLEEP_RATE FLOAT,
    FULL_SLEEP_RATE FLOAT,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (ID, TIMESTAMP)
);

-- Active zone minutes table - fix primary key
CREATE TABLE IF NOT EXISTS ACTIVE_ZONE_MINUTES (
    ID BIGSERIAL,
    USER_ID INT REFERENCES USERS(USER_ID),
    DEVICE_ID TEXT REFERENCES DEVICES(DEVICE_ID),
    TIMESTAMP TIMESTAMPTZ NOT NULL,
    FAT_BURN_MINUTES INT,
    CARDIO_MINUTES INT,
    PEAK_MINUTES INT,
    ACTIVE_ZONE_MINUTES INT,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (ID, TIMESTAMP)
);

-- Activity table - fix primary key
CREATE TABLE IF NOT EXISTS ACTIVITY (
    ID BIGSERIAL,
    USER_ID INT REFERENCES USERS(USER_ID),
    DEVICE_ID TEXT REFERENCES DEVICES(DEVICE_ID),
    TIMESTAMP TIMESTAMPTZ NOT NULL,
    VALUE INT,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (ID, TIMESTAMP)
);

-- Create last_processed_dates table for tracking timestamps
CREATE TABLE IF NOT EXISTS LAST_PROCESSED_DATES (
    METRIC_TYPE TEXT,
    USER_ID INT,
    LAST_PROCESSED_DATE TIMESTAMPTZ NOT NULL,
    UPDATED_AT TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (METRIC_TYPE, USER_ID)
);

-- Convert tables to TimescaleDB hypertables
SELECT
    CREATE_HYPERTABLE('heart_rate', 'timestamp', IF_NOT_EXISTS => TRUE);

SELECT
    CREATE_HYPERTABLE('heart_rate_zones', 'timestamp', IF_NOT_EXISTS => TRUE);

SELECT
    CREATE_HYPERTABLE('spo2', 'timestamp', IF_NOT_EXISTS => TRUE);

SELECT
    CREATE_HYPERTABLE('hrv', 'timestamp', IF_NOT_EXISTS => TRUE);

SELECT
    CREATE_HYPERTABLE('breathing_rate', 'timestamp', IF_NOT_EXISTS => TRUE);

SELECT
    CREATE_HYPERTABLE('active_zone_minutes', 'timestamp', IF_NOT_EXISTS => TRUE);

SELECT
    CREATE_HYPERTABLE('activity', 'timestamp', IF_NOT_EXISTS => TRUE);

-- Create indexes for efficient querying
CREATE INDEX IF NOT EXISTS IDX_HEART_RATE_USER_TIMESTAMP ON HEART_RATE (USER_ID, TIMESTAMP);

CREATE INDEX IF NOT EXISTS IDX_HEART_RATE_ZONES_USER_TIMESTAMP ON HEART_RATE_ZONES (USER_ID, TIMESTAMP);

CREATE INDEX IF NOT EXISTS IDX_SPO2_USER_TIMESTAMP ON SPO2 (USER_ID, TIMESTAMP);

CREATE INDEX IF NOT EXISTS IDX_HRV_USER_TIMESTAMP ON HRV (USER_ID, TIMESTAMP);

CREATE INDEX IF NOT EXISTS IDX_BREATHING_RATE_USER_TIMESTAMP ON BREATHING_RATE (USER_ID, TIMESTAMP);

CREATE INDEX IF NOT EXISTS IDX_AZM_USER_TIMESTAMP ON ACTIVE_ZONE_MINUTES (USER_ID, TIMESTAMP);

CREATE INDEX IF NOT EXISTS IDX_ACTIVITY_USER_TIMESTAMP ON ACTIVITY (USER_ID, TIMESTAMP);